### ISSUE TITLE
Connect to jack server after process callback is initiated

### ISSUE THREAD

**Issue by flxkrmr** [cybercatalyst/qtjack-examples#1]
I think the client should be connected to the jack server after the MyProcessor class is initiated. I have not tested your code, but in my code this was not working and for me it makes more sense if line 33 and 35 are swapped. Please correct my if I'm wrong.

```
QtJack::Client client;
MyProcessor processor(client);

client.connectToServer("attenuator_demo");
client.activate();
```

**Comment by flxkrmr** [comment]
Sorry my fault, it does not work in my code! It must be another problem.

**Comment by jacob3141** [comment]
Could you get the attenuator example to work?

Please contact me via mail if you need more help and don't want to publish your code.

**Comment by flxkrmr** [comment]
Finally it did work in my code. I had something else messed up, but thanks for your help :) I did not try exactly the attenuator example, but something similar.
